version: '3.8'
services:
  auth-svc:
    build: ./auth-service
    container_name: auth-svc
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  payment-svc:
    build: ./payment-service
    container_name: payment-svc
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-svc
    networks:
      - backend

  vas-svc:
    build: ./vas-service
    container_name: vas-svc
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - payment-svc
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

    #  flyway:
    #    image: flyway/flyway:9
    #    depends_on:
    #      mysql:
    #        condition: service_healthy
    #    volumes:
    #      - ./resources/db/migrations:/flyway/sql
    #    command: -url=jdbc:mysql://mysql:3306/exercise -user=myuser -password=mypassword -connectRetries=10 migrate

  zookeeper:
      image: confluentinc/cp-zookeeper:7.3.2
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
  kafka:
      image: confluentinc/cp-kafka:7.3.2
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  backend:
    driver: bridge
